### ISSUE TITLE
Adapter Terminated

### ISSUE THREAD

**Issue by Breseb** [FossyTom/ioBroker.goodwe#8]
Der Adapter wir nach ca. einem Tag durch IoBroker mit der angehängten Meldung terminiert.
Davor werden die Werte immer mal wieder auf 0 zurückgesetzt und neungeholt.

![DACDE397-164D-46F4-A245-552219893A6C](https://user-images.githubusercontent.com/122479477/211888668-228cfd88-8f00-4faa-ab45-d7e081f49a1c.jpeg)

**Comment by FossyTom** [comment]
Please test the V 1.0.3. I have make any changes for the comm

**Comment by Breseb** [comment]
Hi,
I tested the latest 1.0.4 and still get an terminated adapter 
![90F1DCA4-BBF9-420E-B511-387A6566947B](https://user-images.githubusercontent.com/122479477/220169867-202d06de-5a0d-4069-849d-c44a0b4e966f.jpeg)

**Comment by FossyTom** [comment]
I've already tried to localize the problem. But I haven't been able to derive any concrete action darsu yet. I have now helped myself by giving the adapter more memory (see picture). Please test whether this leads to an improvement.
![GoodWe Adapter Memory](https://user-images.githubusercontent.com/55022482/220176586-95942732-f454-4743-9b84-a323f2bfabf8.PNG)

**Comment by Breseb** [comment]
I increased the Memory to 200mb and singe then, i didnt get any termination. This seems to work.
Thx
